<script>
function showResult(str) {
  if (str.length==0) {
    document.getElementById("livesearch").innerHTML="";
    document.getElementById("livesearch").style.border="0px";
    return;
  }
  if (window.XMLHttpRequest) {
    // code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
  } else {  // code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange=function() {
    if (this.readyState==4 && this.status==200) {
      document.getElementById("livesearch").innerHTML=this.responseText;
      document.getElementById("livesearch").style.border="1px solid #A5ACB2";
    }
  }
  xmlhttp.open("GET","livesearch.php?q="+str,true);
  xmlhttp.send();
}
</script>

<!--
<div class="container" >
    <div class="jumbotron">
        <h1 class="display-4" style="text-align: center; font-size: 50px">BENERin</h1>
        <form>
            <input type="text" size="30" style="margin-left: " onkeyup="showResult(this.value)">
            <div id="livesearch"></div>
        </form>
    </div>
</div>
-->
<div class="container">
    <div class="jumbotron">
        <h1 align="center">BENERin</h1><br />
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <input type="text" name="search" id="search" class="form-control" placeholder="Search Paper" />
                    <div id="livesearch"></div>
                </div>
                <div class="table-responsive">
                  <h3 align="center">List Article : <span id="total_records"></span></h3>
                  <table class="table table-striped table-bordered">
                   <thead>
                    <tr style="background-color: #ee161f">
                     <th>id</th>
                     <th>Title</th>
                     <th>Author</th>
                     <th>Released Date</th>
                     <th>Upload Date</th>
                    </tr>
                   </thead>
                   <tbody>
                    
                   </tbody>
                  
                  </table>
               </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){

 fetch_customer_data();

 function fetch_customer_data(query = '')
 {
  $.ajax({
   url:"index/search",
   method:'GET',
   data:{query:query},
   dataType:'json',
   success:function(data)
   {
    $('tbody').html(data.table_data);
    $('#total_records').text(data.total_data);
   }
  })
 }

 $(document).on('keyup', '#search', function(){
  var query = $(this).val();
  fetch_customer_data(query);
 });
});
</script>